Feature/mbx 2446
mindbox-cloud/flutter-sdk pull request #40
Opened 2023-04-25 07:58 UTC by umbrellait-nikolay-silantyev

https://github.com/mindbox-cloud/issues-web-mobile/issues/2446

2023-04-26 07:22 UTC, enotniy approved these changes

2023-04-26 07:22 UTC, enotniy commented on mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
> +    override fun onMethodCall(call: MethodCall, result: Result) {
Не добавлял метод `setLogLevel`?
Или это надо делать не в dart

2023-04-26 07:46 UTC, Vailence commented on mindbox/lib/mindbox.dart
> +  void onInAppDismissed(InAppDismissedHandler handler) {
Кстати говоря надо уточнить этот вопрос и привести однообразно на платформах. Ты вроде говорил что на iOS и click и dismiss срабатывают сразу, верно ?

2023-04-26 07:57 UTC, enotniy commented on mindbox/lib/mindbox.dart
> +  void onInAppDismissed(InAppDismissedHandler handler) {
важный вопрос. Сформулируй, что происходит и давай проверим

2023-04-26 07:58 UTC, umbrellait-nikolay-silantyev commented on mindbox/lib/mindbox.dart
> +  void onInAppDismissed(InAppDismissedHandler handler) {
давайте вынесу этот вопрос в чат, а то мы его в тредах, и дм обсуждали)

2023-04-26 09:52 UTC, Vailence requested changes

2023-04-26 10:37 UTC, umbrellait-nikolay-silantyev commented on mindbox_ios/ios/Classes/SwiftMindboxIosPlugin.swift
> +        NotificationCenter.default.addObserver(forName: NSNotification.Name(rawValue: "receivedPushNotification"), object: nil, queue: nil) { [self] notification in
Договорились, что текущая реализация - не самая лучшая, но не критичная. Необходимо провести ресерч передачи данных пуша из AppDelegateObjc в Swift плагин сдк (либо конформить те же протоколы, но уже в objc классе) и поправить в будущем

2023-04-26 10:38 UTC, umbrellait-nikolay-silantyev commented on mindbox/CHANGELOG.md
> +* Upgrade Android SDK dependency to v2.1.10.
при мерже пропустил, убрал лишнее

2023-04-26 11:02 UTC, umbrellait-nikolay-silantyev commented on mindbox_ios/ios/Classes/SwiftMindboxIosPlugin.swift
> +        let channel = FlutterMethodChannel(name: "mindbox.cloud/flutter-sdk", binaryMessenger: registrar.messenger())
Частично вынес строки в enum. Остальные думаю не имеет смысла выносить, тк они нигде не переиспользуются

2023-04-28 10:48 UTC, umbrellait-nikolay-silantyev commented on mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
> -    companion object {
@enotniy кстати, Егор, думаю ты увидел, но подсвечу, что этот метод убирается. У клиентов с версиями сдк 2.1.+ (мб даже и в последней 2.2.0) он мог остаться, поэтому после обновления билд будет падать с ошибкой. В инструкции об этом [сказано](https://developers.mindbox.ru/docs/android-get-click-flutter)

2023-04-28 10:51 UTC, umbrellait-nikolay-silantyev commented on mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
> -        fun pushClicked(link: String, payload: String) {
@enotniy кстати, Егор, думаю ты увидел, но подсвечу, что этот метод убирается. У клиентов с версиями сдк 2.1.+ (мб даже и в последней 2.2.0) он мог остаться, поэтому после обновления билд будет падать с ошибкой. В инструкции об этом [сказано](https://developers.mindbox.ru/docs/android-get-click-flutter)

2023-04-28 10:53 UTC, enotniy commented on mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
> -        fun pushClicked(link: String, payload: String) {
Главное, чтобы падало при билде, а не в рантайме. Хотя можно было и оставить. Или он не работает?

2023-04-28 10:59 UTC, umbrellait-nikolay-silantyev commented on mindbox_android/android/src/main/kotlin/cloud/mindbox/mindbox_android/MindboxAndroidPlugin.kt
> -        fun pushClicked(link: String, payload: String) {
он с пустым телом сейчас. Хотелось бы уже в инструкции пометить, что такого метода нет, и добавлять при интеграции точно не нужно

2023-05-03 11:10 UTC, merged